# Generated by Django 5.2.6 on 2025-10-20 05:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='mentee_profiles/')),
                ('interests', models.TextField(help_text="e.g., 'Web Development, APIs, Django'")),
                ('current_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('goal', models.TextField(help_text="e.g., 'Get a backend job', 'Build my own project'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='mentor_profiles/')),
                ('bio', models.TextField(help_text='Short intro about your journey', max_length=500)),
                ('headline', models.CharField(help_text="Short tagline like 'Senior Django Developer'", max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(help_text='Years of professional experience', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Rate per session/hour', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('availability', models.JSONField(default=dict, help_text="JSON format: {'mon': ['10:00', '15:00'], 'wed': ['14:00']}")),
                ('session_duration', models.IntegerField(choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes')], default=60, help_text='Default session duration in minutes')),
                ('available_for', models.TextField(help_text="e.g., 'Career Guidance, Code Review, Debugging Help'")),
                ('is_approved', models.BooleanField(default=False)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(related_name='mentors', to='main.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
