# Generated by Django 5.2.6 on 2025-10-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mentorapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='hire_developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('message', models.TextField()),
                ('project_type', models.CharField(max_length=100)),
                ('project_heading', models.CharField(max_length=200)),
                ('project_details', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
