# Generated by Django 5.2.6 on 2025-11-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_make_mentorprofile_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='admin_provided_link',
            field=models.URLField(blank=True, help_text='Link provided by admin when confirming session', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='link_provided_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when admin provided the link', null=True),
        ),
        migrations.DeleteModel(
            name='MentorApplication',
        ),
    ]
