# Generated by Django 5.1.2 on 2025-12-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category_question_option_testattempt_attemptanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_developer',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
