# Generated by Django 5.1.2 on 2026-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_mentorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='answers_selected', to='main.option'),
        ),
    ]
